[project]
id = "jzkqowkvvvhiyktkaisb"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "com.willsigmon.carchat://"

[auth.external.apple]
enabled = true

[auth.email]
enable_signup = false

[db]
port = 54322
shadow_port = 54320
major_version = 17

[studio]
enabled = true
port = 54323

[storage]
enabled = false

[realtime]
enabled = true
